
USE hireatlas;


CREATE TABLE appUser
(
UserID BIGINT IDENTITY(1,1) PRIMARY KEY,
Name  VARCHAR(100)  NOT NULL,
Email VARCHAR(150)  NOT NULL UNIQUE,
Phone VARCHAR(20),
Age INT CHECK (Age >= 15),
Password VARCHAR(255)  NOT NULL,
CV_path  VARCHAR(255)
);

CREATE TABLE Post (
PostID  BIGINT IDENTITY(1,1) PRIMARY KEY,
CreatorID BIGINT NOT NULL,
JobTitle  VARCHAR(150) NOT NULL,
Description VARCHAR(1000),
Location VARCHAR(150),
Category VARCHAR(100),
EstimateSalary DECIMAL(18,2)  CHECK (EstimateSalary >= 0),
isActive VARCHAR(10) NOT NULL
DEFAULT 'Active'
CONSTRAINT CHK_Post_isActive
CHECK (isActive IN ('Active', 'Inactive')),
CreatedAt DATETIME DEFAULT GETDATE(),
CONSTRAINT FK_Post_User
FOREIGN KEY (CreatorID) REFERENCES appUser(UserID)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Application (
ApplicationID BIGINT IDENTITY(1,1) PRIMARY KEY,
PostID BIGINT NOT NULL,
ApplicantID BIGINT NOT NULL,
Status VARCHAR(50)  DEFAULT 'Pending'
CONSTRAINT CHK_App_Status
CHECK (Status IN ('Pending', 'Reviewed', 'Accepted', 'Rejected')),
ApplicationDate DATE         DEFAULT GETDATE(),
 CV_path  VARCHAR(255),

CONSTRAINT UQ_Application UNIQUE (PostID, ApplicantID),
CONSTRAINT FK_Application_Post
FOREIGN KEY (PostID) REFERENCES Post(PostID)
ON DELETE CASCADE ON UPDATE CASCADE,

CONSTRAINT FK_Application_User
FOREIGN KEY (ApplicantID) REFERENCES appUser(UserID)
ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE User_Education (
EduID BIGINT IDENTITY(1,1) PRIMARY KEY,
UserID  BIGINT NOT NULL,
InstituteName VARCHAR(200),
Level VARCHAR(100),
DegreeName  VARCHAR(150),
Grade  DECIMAL(5,2),
StartDate  DATE,
EndDate   DATE,

 CONSTRAINT FK_Education_User
  FOREIGN KEY (UserID) REFERENCES appUser(UserID)
  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE User_Experience (
 ExpID  BIGINT IDENTITY(1,1) PRIMARY KEY,
 UserID  BIGINT NOT NULL,
CompanyName VARCHAR(200),
 JobTitle  VARCHAR(150),
 Description VARCHAR(1000),
 StartDate  DATE,
EndDate   DATE,
CONSTRAINT FK_Experience_User
 FOREIGn KEY (UserID) REFERENCES appUser(UserID)
 ON DELETE CASCADE ON UPDATE CASCADE
);